### ISSUE TITLE
About iterations

### ISSUE THREAD

**Issue by PGCJ** [JackAndCole/Automatic-ECG-Classification-Using-Continuous-Wavelet-Transform-and-Convolutional-Neural-Network#1]
Can you tell me how many times your epoch is?

**Comment by JackAndCole** [comment]
max_epochs=30,

**Comment by PGCJ** [comment]
> max_epochs=30,

3Q very much。I am leanring your code。It is very simpler and stronger than my code.

**Comment by PGCJ** [comment]
hello，i am sorry  to bother you, but can I ask you how to identify type F in MIT-BIH DB? i tried a lot of methods in it and tired reproduce other people's papers, but them do not work.

**Comment by PGCJ** [comment]
> max_epochs=30,

hello，i am sorry to bother you, but can I ask you how to identify type F in MIT-BIH DB? i tried a lot of methods in it and tired reproduce other people's papers, but them do not work.

**Comment by JackAndCole** [comment]
In our model, we directly input the F category data into the model for multi-classification, which can achieve better performance. However, it should be noted that the F category has a relatively small number of categories and there is a serious data imbalance. In some models, some data balancing work may be needed.

**Comment by PGCJ** [comment]
> In our model, we directly input the F category data into the model for multi-classification, which can achieve better performance. However, it should be noted that the F category has a relatively small number of categories and there is a serious data imbalance. In some models, some data balancing work may be needed.

This means that class F can be recognized, but it is limited by the super-imbalance of the MIT-BIH dataset, resulting in poor recognition.
Have you reproduced other people's papers? I found that many of their classifications for class F were particularly high, but according to their description, I could not reproduce any of them.
thank you reply very much. 
maybe we could use Chinese communication？

**Comment by JackAndCole** [comment]
微信号发我一下

**Comment by PGCJ** [comment]
> 微信号发我一下

cjj10041104
